### PR TITLE
Bind dockerd socket to 0.0.0.0:2375

### PR DESCRIPTION
**Pull request by brb**
So that we can connect to it from a hypervisor host. This will be needed by some e2e tests, which will need to run "docker" cli from a GH runner, but targeting dockerd running in a LVH VM.

### CODE REVIEW

**Review by kkourt — APPROVED** [review]
I don't think this will break the tetragon e2e tests, but would nice to get an ACK from @willfindlay as well.

**Comment by willfindlay** [comment]
Double checking this today.

**Review by willfindlay — APPROVED** [review]
~Yep all good on the Tetragon side.~

**Review by willfindlay — CHANGES_REQUESTED** [review]
Spoke too soon, I did find an issue in Tetragon CI with this. Taking a closer look now.

**Review by willfindlay — APPROVED** [review]
Yep all good on the Tetragon side.

**Pull request merged**
