### PR TITLE
_data: Ensure kernel loads sysctl on boot

### PR DESCRIPTION
**Pull request by jschwinger233**

### CODE REVIEW

**Comment by julianwiedmann** [comment]
@jschwinger233 let me know if you need help with testing the CI build in cilium/cilium from a repo branch :)

**Comment by jschwinger233** [comment]
@julianwiedmann I'm waiting for lvh image build and intend to manually update workflow yamls for test, does that sound good :grimacing:

**Comment by borkmann** [comment]
Related: https://bugs.launchpad.net/ubuntu/+source/procps/+bug/50093
I wonder why we only hit these now on (kernel) upgrade..

**Comment by borkmann** [comment]
Should this instead be configured in /etc/sysctl.d/99-sysctl.conf ?

**Comment by jschwinger233** [comment]
Looking at https://github.com/cilium/cilium/pull/35583, ci-e2e-upgrade no longer fails on "Start conn-disrupt-test". I think this PR works, ready for review.

**Review by borkmann — APPROVED** [review]

**Pull request merged**
