### PR TITLE
lvh: Add net branch of bpf-next

### PR DESCRIPTION
**Pull request by borkmann**
For testing we also need the net branch of bpf-next.

### CODE REVIEW

**Review by mtardy — APPROVED** [review]
Looks good, let's see the output of the workflows :)

**Comment by borkmann** [comment]
Hm, looks like we hit timeout :/

**Comment by mtardy** [comment]
> Hm, looks like we hit timeout :/

looks like an infra flake:
> Error: ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": Get "https://auth.docker.io/token?account=githubactions&scope=repository%3Amoby%2Fbuildkit%3Apull&service=registry.docker.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Let's try again

**Review by kkourt — APPROVED** [review]

**Comment by borkmann** [comment]
Nice looks like it worked out! :) Thanks all :wave:

**Pull request merged**
